stages:
  - test
  - build
  - deploy

backend-test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:10.0
  script:
    - cd Backend
    - dotnet restore
    - dotnet test --no-restore

backend-build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:10.0
  script:
    - cd Backend
    - dotnet publish ECommerce.API -c Release -o publish
  artifacts:
    paths:
      - Backend/publish/

deploy-backend-staging:
  stage: deploy
  image: alpine:latest
  needs:
    - backend-build
  script:
    - echo "Deploy backend"
  environment:
    name: staging
    url: https://staging-api.shipshop.example.com